# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server_window(object):
    def setupUi(self, server_window):
        server_window.setObjectName("server_window")
        server_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(server_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.port_label = QtWidgets.QLabel(self.centralwidget)
        self.port_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 3, 1, 1, 1)
        self.size_label = QtWidgets.QLabel(self.centralwidget)
        self.size_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.size_label.setObjectName("size_label")
        self.gridLayout.addWidget(self.size_label, 3, 3, 1, 1)
        self.entered_filename = QtWidgets.QLineEdit(self.centralwidget)
        self.entered_filename.setObjectName("entered_filename")
        self.gridLayout.addWidget(self.entered_filename, 4, 2, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.start_button.setObjectName("start_button")
        self.gridLayout.addWidget(self.start_button, 5, 0, 1, 2)
        self.entered_size = QtWidgets.QLineEdit(self.centralwidget)
        self.entered_size.setObjectName("entered_size")
        self.gridLayout.addWidget(self.entered_size, 4, 3, 1, 1)
        self.entered_port = QtWidgets.QLineEdit(self.centralwidget)
        self.entered_port.setObjectName("entered_port")
        self.gridLayout.addWidget(self.entered_port, 4, 1, 1, 1)
        self.filename_label = QtWidgets.QLabel(self.centralwidget)
        self.filename_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.filename_label.setObjectName("filename_label")
        self.gridLayout.addWidget(self.filename_label, 3, 2, 1, 1)
        self.checkBox_speed_lim = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_speed_lim.setObjectName("checkBox_speed_lim")
        self.gridLayout.addWidget(self.checkBox_speed_lim, 3, 4, 1, 1)
        self.console = QtWidgets.QTextEdit(self.centralwidget)
        self.console.setMaximumSize(QtCore.QSize(16777215, 80))
        self.console.setObjectName("console")
        self.gridLayout.addWidget(self.console, 2, 0, 1, 5)
        self.graph_field = QtWidgets.QWidget(self.centralwidget)
        self.graph_field.setObjectName("graph_field")
        self.gridLayout.addWidget(self.graph_field, 1, 0, 1, 5)
        self.lineEdit_speed_lim = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_speed_lim.setObjectName("lineEdit_speed_lim")
        self.gridLayout.addWidget(self.lineEdit_speed_lim, 4, 4, 1, 1)
        self.change_to_client_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_to_client_button.setMaximumSize(QtCore.QSize(400, 16777215))
        self.change_to_client_button.setObjectName("change_to_client_button")
        self.gridLayout.addWidget(self.change_to_client_button, 5, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        server_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(server_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_connection_type = QtWidgets.QMenu(self.menu)
        self.menu_connection_type.setObjectName("menu_connection_type")
        self.menu_lost_packets = QtWidgets.QMenu(self.menu)
        self.menu_lost_packets.setObjectName("menu_lost_packets")
        server_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(server_window)
        self.statusbar.setObjectName("statusbar")
        server_window.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(server_window)
        self.action.setObjectName("action")
        self.action_remove_graph = QtWidgets.QAction(server_window)
        self.action_remove_graph.setObjectName("action_remove_graph")
        self.action_TCP = QtWidgets.QAction(server_window)
        self.action_TCP.setEnabled(False)
        self.action_TCP.setObjectName("action_TCP")
        self.actionddd = QtWidgets.QAction(server_window)
        self.actionddd.setObjectName("actionddd")
        self.action_UDP_ = QtWidgets.QAction(server_window)
        self.action_UDP_.setObjectName("action_UDP_")
        self.action_lost_packets_on = QtWidgets.QAction(server_window)
        self.action_lost_packets_on.setObjectName("action_lost_packets_on")
        self.action_lost_packets_off = QtWidgets.QAction(server_window)
        self.action_lost_packets_off.setEnabled(False)
        self.action_lost_packets_off.setObjectName("action_lost_packets_off")
        self.menu_connection_type.addAction(self.action_TCP)
        self.menu_connection_type.addSeparator()
        self.menu_connection_type.addAction(self.action_UDP_)
        self.menu_lost_packets.addAction(self.action_lost_packets_on)
        self.menu_lost_packets.addAction(self.action_lost_packets_off)
        self.menu.addAction(self.action_remove_graph)
        self.menu.addAction(self.menu_connection_type.menuAction())
        self.menu.addAction(self.menu_lost_packets.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(server_window)
        QtCore.QMetaObject.connectSlotsByName(server_window)

    def retranslateUi(self, server_window):
        _translate = QtCore.QCoreApplication.translate
        server_window.setWindowTitle(_translate("server_window", "Имитатор TCP соединения (сервер)"))
        self.port_label.setText(_translate("server_window", "Порт:"))
        self.size_label.setText(_translate("server_window", "Размер сообщения:"))
        self.start_button.setText(_translate("server_window", "Старт"))
        self.filename_label.setText(_translate("server_window", "Имя файла:"))
        self.checkBox_speed_lim.setText(_translate("server_window", " Отсечение аномальных значений:"))
        self.change_to_client_button.setText(_translate("server_window", "Переход к окну \"Клиент\""))
        self.menu.setTitle(_translate("server_window", "Опции"))
        self.menu_connection_type.setTitle(_translate("server_window", "Тип соединения"))
        self.menu_lost_packets.setTitle(_translate("server_window", "Отображение полученных пакетов"))
        self.action.setText(_translate("server_window", "Опции"))
        self.action_remove_graph.setText(_translate("server_window", "Очистить график"))
        self.action_TCP.setText(_translate("server_window", "TCP"))
        self.actionddd.setText(_translate("server_window", "ddd"))
        self.action_UDP_.setText(_translate("server_window", "UDP"))
        self.action_lost_packets_on.setText(_translate("server_window", "Включить"))
        self.action_lost_packets_off.setText(_translate("server_window", "Выключить"))
